### ISSUE TITLE
ecpool 0.4.0 does not handling connecton reconnect properly

### ISSUE THREAD

**Issue by sufish** [emqx/ecpool#11]
Take emqx_auth_redis for an example,  which uses ecpool as pooling solution. 

enable this plugin, check redis connection using client-list,  you can see there are 8 connections by defaut. 

then restart redis-server, check connections again, there are still 8 connections, good. 

then restart redis-server again, check connections , the 8 connections are gone. 

if i compile this plugin using ecpool 0.3.0, then everything is fine, connections can be re-establish  
after every redis-server restart.

i have review the code of ecpool 0.4.0, seems that the bug might happens in following code:

```erlang
handle_info(reconnect, State = #state{opts = Opts, on_reconnect = OnReconnect}) ->
    case catch connect(State) of
        {ok, Client} ->
            handle_reconnect(Client, OnReconnect),
            {noreply, State#state{client = Client}};
        {{ok, Client}, #{supervisees := SupPids} = _SupOpts} ->
            handle_reconnect(Client, OnReconnect),
            {noreply, State#state{client = Client, supervisees = SupPids}};
        {Err, _Reason} when Err =:= error orelse Err =:= 'EXIT' ->
            reconnect(proplists:get_value(auto_reconnect, Opts), State)
    end;
``` 

during reconnect there is no erlang:link and set supervisees, so next reconnect will not be triggered.

**Comment by terry-xiaoyu** [comment]
@sufish Thanks for pointing out this issue! The problem is caused by my [last commit](https://github.com/emqx/ecpool/commit/d963056757841c4d682563bf98f893b722979b05), which allows ecpool_worker to monitor more than one PIDs.

The following clause allows the caller to provide an additional option `supervisees` -- a list of Pids that it would like to be monitored by the ecpool_woker:

https://github.com/emqx/ecpool/blob/253ffcdb5e7f01c51d277fedc416334634703168/src/ecpool_worker.erl#L98

The root cause is the option `supervisees` is not set after reconnected.

Could you create a Pull Request to master branch?

**Comment by terry-xiaoyu** [comment]
You can find me at WeChat, 18253232330.
